### ISSUE TITLE
Koa Support

### ISSUE THREAD

**Issue by ZempTime** [Urigo/SOFA#101]
Hey! I've just stumbled across this project, and I'm extremely interested. I was curious if there was any intent or pathways to support usage in [Koa](https://koajs.com/).

Of note is [koa-connect](https://github.com/vkurchatkin/koa-connect).

**Comment by ardatan** [comment]
@ZempTime Doesn't `koa-connect` work with SOFA and Koa?

**Comment by ZempTime** [comment]
I'm working on a base koa template right now, and this will be one of the things I check into. I'll post back with results!

**Comment by ardatan** [comment]
@ZempTime I'm closing this issue right now. Feel free to open new one if you still have problem with Koa and Sofa :)

**Comment by ZempTime** [comment]
I haven't been able to get this working:
```
TypeError: res.status is not a function
    at defaultErrorHandler (/Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:187:21)
    at /Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:191:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{"level":50,"time":1574360669764,"pid":31637,"hostname":"C02XD4Q8JGH6","msg":"Error Handler: {}","v":1}
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at resolveVariable (/Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/parse.js:27:70)
    at Object.parseVariable (/Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/parse.js:6:16)
    at info.variables.reduce (/Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:165:35)
    at Array.reduce (<anonymous>)
    at /Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:163:47
    at Generator.next (<anonymous>)
    at /Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zempelc/code/maritz/koa-ms/node_modules/sofa-api/dist/express.js:4:12)
```
I'll definitely revisit this and try again later. For the situation I'm in, it ends up we're not gonna be able to graphql-first, so this will get another look later once it becomes the proper time to look into code generation as a whole.
