### ISSUE TITLE
Integrating SOFA with a Sequelize GQL schema generator

### ISSUE THREAD

**Issue by realies** [Urigo/SOFA#226]
Attempting to use SOFA with https://github.com/almost-full-stack/sequelize-graphql-schema, although not getting parameter endpoints or query arguments from the schema it provides.

The following request replies as expected via GraphiQL
```
{
  fileGet(id: "xyz") {
    name
    createdAt
  } 
}
```

The following file-associated routes get generated for the REST API:
```
GET /rest/file-get
POST /rest/file-add
POST /rest/file-edit
POST /rest/file-delete
```

Although, accessing `GET /rest/file-get` replies with:
```
TypeError: String cannot represent value: undefined
    at GraphQLScalarType.serializeString [as serialize] (/app/node_modules/graphql/type/scalars.js:159:9)
    at resolveVariable (/app/node_modules/sofa-api/dist/parse.js:24:30)
    at Object.parseVariable (/app/node_modules/sofa-api/dist/parse.js:6:16)
    at /app/node_modules/sofa-api/dist/express.js:165:35
    at Array.reduce (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:163:47
    at Generator.next (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/sofa-api/dist/express.js:4:12)
    at /app/node_modules/sofa-api/dist/express.js:162:35
    at /app/node_modules/sofa-api/dist/express.js:213:25
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
    at router (/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

Accessing `GET /rest/file-get?id=xyz` replies with:
```
TypeError: Int cannot represent non-integer value: undefined
    at GraphQLScalarType.serializeInt [as serialize] (/app/node_modules/graphql/type/scalars.js:43:11)
    at resolveVariable (/app/node_modules/sofa-api/dist/parse.js:24:30)
    at Object.parseVariable (/app/node_modules/sofa-api/dist/parse.js:6:16)
    at /app/node_modules/sofa-api/dist/express.js:165:35
    at Array.reduce (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:163:47
    at Generator.next (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/sofa-api/dist/express.js:4:12)
    at /app/node_modules/sofa-api/dist/express.js:162:35
    at /app/node_modules/sofa-api/dist/express.js:213:25
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
    at router (/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

Posting (`curl -X POST http://localhost/rest/file-add -d '{ id: "zyx", name: "test" }'`) replies with:
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at resolveVariable (/app/node_modules/sofa-api/dist/parse.js:27:70)
    at Object.parseVariable (/app/node_modules/sofa-api/dist/parse.js:6:16)
    at /app/node_modules/sofa-api/dist/express.js:165:35
    at Array.reduce (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:163:47
    at Generator.next (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/sofa-api/dist/express.js:4:12)
    at /app/node_modules/sofa-api/dist/express.js:162:35
    at /app/node_modules/sofa-api/dist/express.js:213:25
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
    at router (/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

Would it be possible for GQL schema generators to plug in SOFA without the need for writing extra GQL definitions?

**Comment by ardatan** [comment]
@realies In first `GET` request, you need to provide `ID` in the URL like below;
`/rest/file-get/ID`
In the second one, the given JSON is not valid;
`{ "id": "zyx", "name": "test" }`
Keys are also needed to be between `"` in JSON.

**Comment by realies** [comment]
@ardatan, thanks for the prompt reply. The `/rest/file-get/:id` path unfortunately does not exist.

`curl -X GET http://localhost/rest/file-get/xyz`
```
Cannot GET /rest/file-get/xyz
```

Using a valid JSON does not produce a much different result.

`curl -X POST http://localhost/rest/file-add -d '{ "id": "zyx", "name": "test" }'`
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at resolveVariable (/app/node_modules/sofa-api/dist/parse.js:27:70)
    at Object.parseVariable (/app/node_modules/sofa-api/dist/parse.js:6:16)
    at /app/node_modules/sofa-api/dist/express.js:165:35
    at Array.reduce (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:163:47
    at Generator.next (<anonymous>)
    at /app/node_modules/sofa-api/dist/express.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/sofa-api/dist/express.js:4:12)
    at /app/node_modules/sofa-api/dist/express.js:162:35
    at /app/node_modules/sofa-api/dist/express.js:213:25
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
    at router (/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by Yehonal** [comment]
have you tried to use our new version? it's under feature/refactor branch.

We will move on master soon but you can already try it

**Comment by ardatan** [comment]
Feel free to open a new issue if the problem still persists.
