### ISSUE TITLE
queries not executing

### ISSUE THREAD

**Issue by sandeepkhan** [Urigo/SOFA#27]
hi,

i tried integrating sofa api my current set of schema.

whenever i try to hit the /api routes, it throws me this error. Is there a docs where i can find how i can query ?

Error: Field "node" of type "Node" must have a selection of subfields. Did you mean "node { ... }"?

GraphQL request (4:5)
3:     nodeId
4:     node(nodeId: $queryNodeNodeId)
       ^
5:   }

    at /Users/sandeep/Documents/projects/dev/master_registry/node_modules/sofa-api/src/express.ts:237:13
    at step (/Users/sandeep/Documents/projects/dev/master_registry/node_modules/sofa-api/dist/express.js:43:23)
    at Object.next (/Users/sandeep/Documents/projects/dev/master_registry/node_modules/sofa-api/dist/express.js:24:53)
    at fulfilled (/Users/sandeep/Documents/projects/dev/master_registry/node_modules/sofa-api/dist/express.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kamilkisiela** [comment]
@sandeepkumardev could you share a minimal schema? Something I could try it out and test?

**Comment by ardatan** [comment]
Closing this issue now. If the problem persists, feel free to open a new one.
