### ISSUE TITLE
TypeError: sofa is not a function at Object.<anonymous>

### ISSUE THREAD

**Issue by vesvello** [Urigo/SOFA#38]
Im trying to implement sofa.

This is so far what I have:
```js
const sofa = require('sofa-api');
const express = require('express');
const app = express();
const { makeExecutableSchema } = require('graphql-tools');
const fs = require('fs');
const resolvers = require('./graphql/resolvers');
const {
  gql
} = require('apollo-server-express');
const typeDefs = gql(
  fs.readFileSync(__dirname.concat('/graphql/schema.graphql'), 'utf8')
);
const schema = makeExecutableSchema({
  typeDefs,
  resolvers: resolvers,
});
app.use(
  sofa({
    schema
  })
);
```

I get as response:
```
TypeError: sofa is not a function
    at Object.<anonymous> (/Applications/MAMP/htdocs/claro360/products360/src/sofa.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Applications/MAMP/htdocs/claro360/products360/src/server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

Any help on this?

Thanks in advance

**Comment by oalcantar** [comment]
Hi, instead of this code

```
app.use(
  sofa({
     schema
  })
);
```

try this code

```
app.use(
  sofa.useSofa({
    schema
  })
);
```

I hope this the helps you

**Comment by ardatan** [comment]
This doesn't look like an issue, but it looks like a confusion between CommonJS and ESM.
