### ISSUE TITLE
Unknown type Upload

### ISSUE THREAD

**Issue by vesvello** [Urigo/SOFA#47]
I got this error when i try to implement sofa:

(GrapdhQL has a upload function)

Error: Unknown type "Upload". Did you mean "Float"?
    at assertValidSDL (/node_modules/graphql/validation/validate.js:80:11)
    at Object.buildASTSchema (/node_modules/graphql/utilities/buildASTSchema.js:69:34)
    at Object.buildSchemaFromTypeDefinitions (/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.<anonymous> (/src/server.js:52:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by ardatan** [comment]
`Upload` is not part of GraphQL, it is a custom scalar. You can define `Upload` scalar by yourself inside the schema,
